version: '3.9'
services:
  client:
    image: nginx:latest
    ports:
      - '80:80'
    volumes: 
      - ./client/build:/usr/share/nginx/html:ro
    restart: always
    networks:
      - piano-network
    depends_on:
      - server
      - db
      
  server:
    image: piano-server:latest
    ports:
      - '8000:8000'
    volumes:
      - ./server/files:/usr/src/app/files
    restart: always
    networks:
      - piano-network
    depends_on:
      - db
      
  db:
    image: postgres:latest
    volumes:
      - piano-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
    restart: always
    networks:
      - piano-network
      
volumes:
  piano-db-volume:
    driver: local
    name: piano-db-volume
      
networks:
  piano-network:
    driver: bridge
    name: piano-network